export const ADD_SERVER = 'ADD_SERVER';
export const GET_SERVERS = 'GET_SERVERS';
export const DELETE_SERVER = 'DELETE_SERVER';
export const SERVER_ERROR = 'SERVER_ERROR';

export const TOGGLE_CONSOLE = 'TOGGLE_CONSOLE';
export const TOGGLE_ADD_PI_MODAL = 'TOGGLE_ADD_PI_MODAL';
export const TOGGLE_ADD_HOST_MODAL = 'TOGGLE_ADD_HOST_MODAL';
export const TOGGLE_CONFIRM_POWER_MODAL = 'TOGGLE_CONFIRM_POWER_MODAL';
export const TOGGLE_USER_SETTINGS_MODAL = 'TOGGLE_USER_SETTINGS_MODAL';
export const TOGGLE_PENDING_USER_LIST_MODAL = 'TOGGLE_PENDING_USER_LIST_MODAL';

export const ADD_HOST = 'ADD_HOST';
export const DELETE_HOST = 'DELETE_HOST';
export const SET_SERVER_NAME = 'SET_SERVER_NAME';
export const ADD_HOST_TO_SERVER = 'ADD_HOST_TO_SERVER';
export const TOGGLE_POWER = 'TOGGLE_POWER';

export const LOGIN = 'LOGIN';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';

export const GET_USER = 'GET_USER';
