export const ADD_SERVER = 'ADD_SERVER';
export const GET_SERVERS = 'GET_SERVERS';
export const REMOVE_SERVER = 'REMOVE_SERVER';
export const SERVER_ERROR = 'REMOVE_SERVER';

export const TOGGLE_CONSOLE = 'TOGGLE_CONSOLE';
export const TOGGLE_ADD_PI_MODAL = 'TOGGLE_ADD_PI_MODAL';
export const TOGGLE_CONFIRM_POWER_MODAL = 'TOGGLE_CONFIRM_POWER_MODAL';
export const TOGGLE_USER_SETTINGS_MODAL = 'TOGGLE_USER_SETTINGS_MODAL';
export const TOGGLE_PENDING_USER_LIST_MODAL = 'TOGGLE_PENDING_USER_LIST_MODAL';

export const ADD_HOST = 'ADD_HOST';
